name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18' # Ensure you specify a Node.js version

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: Real-Time-Chat-Frontend

      - name: Typecheck and Build Frontend
        run: npm run build
        working-directory: Real-Time-Chat-Frontend

      - name: Install Backend Dependencies
        run: npm install
        working-directory: Real-Time-Chat-Server

      - name: Copy .env.example Files
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;
        working-directory: Real-Time-Chat-Server

      - name: Typecheck and Build Backend
        run: npm run build
        working-directory: Real-Time-Chat-Server
